### ISSUE TITLE
云编译能过，本地编译过不去

### ISSUE THREAD

**Issue by MXJNZ6** [esirplayground/luci-app-LingTiGameAcc#2]
本地提示这个文件夹没文件还是啥好像
po2lmo ./po/zh-cn/lingti.po /home/x/lede/build_dir/target-aarch64_cortex-a53_musl/luci-app-LingTiGameAcc-20210302/.pkgdir/luci-app-LingTiGameAcc/usr/lib/lua/luci/i18n/lingti.zh-cn.lmo
bash: po2lmo: command not found
make[3]: *** [Makefile:92: /home/x/lede/build_dir/target-aarch64_cortex-a53_musl/luci-app-LingTiGameAcc-20210302/.pkgdir/luci-app-LingTiGameAcc.installed] Error 127

**Comment by esirplayground** [comment]
po2lmo是luci-base自带的工具，请确认编译环境中未缺失luci-base
